### ISSUE TITLE
[Milestone 5] Talleres de formación a los clubes de ciencia

### ISSUE THREAD

**Issue by lauramb8909** [lauramb8909/Moncora#4]
Los auxiliares iniciarán los talleres en las instituciones:

- [ ] Colegio Normal: Marzo /2023
- [ ] Colegio Santander: Marzo /2023
- [ ] Instituto Damaso Zapata: abril /2023
- [ ] Institución educativa comuneros
- [ ] Colegio fundeUis : Marzo /2023
