### ISSUE TITLE
[Milestone 4] Contenido Talleres

### ISSUE THREAD

**Issue by lauramb8909** [lauramb8909/Moncora#5]
Se realizará un repositorio con los contenidos de los talleres. Estos talleres se dictarán en cuatro módulos, que son:

- [x] Ciencia ciudadana y método científico
- [x] Cambio climático
- [x] Equipos de monitoreo ambiental
- [ ] Programación en Python

Página web con contenidos: [link](https://class.redclara.net/halley/moncora/intro.html)

**Comment by lauramb8909** [comment]
Los auxiliares se reúnen con los coordinadores del proyecto cada semana para asignar tareas sobre el contenido de los talleres y realimentación sobre el avance de los mismos en los colegios.
